# Uncomment the next line to define a global platform for your project
  platform :ios, '12.0'

target 'FlickrApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FlickrApp
	pod 'SnapKit'
	pod 'Moya'
	pod 'Kingfisher'
	pod 'IQKeyboardManagerSwift'
end
